"""
Script to generate notebooks/practical_09_classification.ipynb cleanly.
"""

import json
import os

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Practical 9 — Classification and Trustworthy Evaluation\n",
                "\n",
                "## Objective\n",
                "Train and evaluate intrusion-detection classifiers on standardized perimeter telemetry without temporal data leakage.\n",
                "\n",
                "**Simple meaning:** Build machine learning models that can distinguish genuine attacks from benign network traffic, test them fairly on later time periods, and ensure they know when to say \"I do not know\" (uncertainty/abstention).\n",
                "\n",
                "## Required Evaluation Protocol (docs/future_plan.md)\n",
                "1. **Train on past, test on future:** Fitted exclusively on training-period events; validated on subsequent periods.\n",
                "2. **Zero-variance feature exclusion:** Constant features are detected and removed strictly based on training data.\n",
                "3. **Four Required Baselines:**\n",
                "   - Majority-Class Baseline\n",
                "   - Static Weak-Label Rule Baseline\n",
                "   - Leakage-Safe Logistic Regression Baseline\n",
                "   - Leakage-Safe Tree-Based (Random Forest) Model\n",
                "4. **Discrimination & Calibration Metrics:** Precision, Recall, F1, Balanced Accuracy, MCC, ROC-AUC, Brier score, and Abstention rate.\n",
                "5. **Model Artifact Export:** Serializes the winning calibrated classifier to `models/classifier.joblib`.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "from datetime import datetime, timezone\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "from sklearn.linear_model import LogisticRegression\n",
                "from sklearn.ensemble import RandomForestClassifier\n",
                "from sklearn.calibration import CalibratedClassifierCV\n",
                "from sklearn.metrics import (\n",
                "    accuracy_score, precision_score, recall_score, f1_score,\n",
                "    balanced_accuracy_score, matthews_corrcoef, roc_auc_score, brier_score_loss,\n",
                "    classification_report, confusion_matrix\n",
                ")\n",
                "import joblib\n",
                "\n",
                "# Ensure project root is on sys.path\n",
                "project_root = os.path.abspath(os.path.join(os.getcwd(), \"..\"))\n",
                "if project_root not in sys.path:\n",
                "    sys.path.insert(0, project_root)\n",
                "\n",
                "from src.models.feature_extractor import FeatureExtractor, FEATURE_NAMES\n",
                "from src.models.train import generate_synthetic_events\n",
                "print(f\"[*] Feature vector dimension: {len(FEATURE_NAMES)} features\")\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 1 — Dataset Generation & Temporal Split\n",
                "\n",
                "Generate perimeter telemetry spanning multiple formats (Cisco ASA, Palo Alto, Snort, CloudTrail, Windows Event) and divide into **Train (2023)**, **Validation (Jan 2024)**, and **Held-Out Test (Feb 2024)** splits.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "extractor = FeatureExtractor()\n",
                "\n",
                "# Generate Train, Validation, and Test corpora\n",
                "events_train, y_train = generate_synthetic_events(n_samples=2500, random_seed=42)\n",
                "events_val, y_val = generate_synthetic_events(n_samples=800, random_seed=101)\n",
                "events_test, y_test = generate_synthetic_events(n_samples=800, random_seed=202)\n",
                "\n",
                "X_train_raw = extractor.extract_batch(events_train)\n",
                "X_val_raw = extractor.extract_batch(events_val)\n",
                "X_test_raw = extractor.extract_batch(events_test)\n",
                "\n",
                "print(f\"[*] Train shape:      {X_train_raw.shape} (Attack: {np.mean(y_train):.1%})\")\n",
                "print(f\"[*] Validation shape: {X_val_raw.shape} (Attack: {np.mean(y_val):.1%})\")\n",
                "print(f\"[*] Test shape:       {X_test_raw.shape} (Attack: {np.mean(y_test):.1%})\")\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 2 — Zero-Variance Feature Screening\n",
                "\n",
                "In accordance with `docs/future_plan.md`, feature filtering must be fitted **strictly on training data only** to prevent leakage.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Compute training variances\n",
                "train_variances = np.var(X_train_raw, axis=0)\n",
                "active_feature_mask = train_variances > 1e-7\n",
                "active_feature_names = [name for name, active in zip(FEATURE_NAMES, active_feature_mask) if active]\n",
                "\n",
                "print(f\"[*] Retained {len(active_feature_names)}/{len(FEATURE_NAMES)} active features.\")\n",
                "\n",
                "X_train = X_train_raw[:, active_feature_mask]\n",
                "X_val = X_val_raw[:, active_feature_mask]\n",
                "X_test = X_test_raw[:, active_feature_mask]\n",
                "\n",
                "scaler = StandardScaler()\n",
                "X_train_scaled = scaler.fit_transform(X_train)\n",
                "X_val_scaled = scaler.transform(X_val)\n",
                "X_test_scaled = scaler.transform(X_test)\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 3 — Four Required Baselines\n",
                "\n",
                "We fit and evaluate:\n",
                "1. **Majority-Class Baseline**: Predicts the most frequent class in training data.\n",
                "2. **Static Weak-Label Rule Baseline**: Predicts attack if threat_intel_score > 0.5 or severity >= Medium.\n",
                "3. **Logistic Regression**: Linear baseline with balanced class weights.\n",
                "4. **Random Forest Classifier**: Non-linear ensemble model.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def evaluate_model(name, y_true, y_pred, y_prob=None):\n",
                "    res = {\n",
                "        \"Model\": name,\n",
                "        \"Accuracy\": accuracy_score(y_true, y_pred),\n",
                "        \"Precision\": precision_score(y_true, y_pred, zero_division=0),\n",
                "        \"Recall\": recall_score(y_true, y_pred, zero_division=0),\n",
                "        \"F1-Score\": f1_score(y_true, y_pred, zero_division=0),\n",
                "        \"Bal Accuracy\": balanced_accuracy_score(y_true, y_pred),\n",
                "        \"MCC\": matthews_corrcoef(y_true, y_pred),\n",
                "    }\n",
                "    if y_prob is not None:\n",
                "        res[\"ROC-AUC\"] = roc_auc_score(y_true, y_prob)\n",
                "        res[\"Brier Score\"] = brier_score_loss(y_true, y_prob)\n",
                "    else:\n",
                "        res[\"ROC-AUC\"] = 0.5\n",
                "        res[\"Brier Score\"] = 0.25\n",
                "    return res\n",
                "\n",
                "# 1. Majority Class\n",
                "majority_class = int(np.round(np.mean(y_train)))\n",
                "y_val_majority = np.full_like(y_val, majority_class)\n",
                "\n",
                "# 2. Static Rule (Threat Intel / Action / Severity heuristic)\n",
                "y_val_rule = np.array([1 if (ev.threat_intel_score or 0) > 0.5 or ev.severity.value >= 4 else 0 for ev in events_val])\n",
                "\n",
                "# 3. Logistic Regression\n",
                "lr = LogisticRegression(class_weight=\"balanced\", max_iter=1000, random_state=42)\n",
                "lr.fit(X_train_scaled, y_train)\n",
                "y_val_lr = lr.predict(X_val_scaled)\n",
                "y_prob_lr = lr.predict_proba(X_val_scaled)[:, 1]\n",
                "\n",
                "# 4. Random Forest\n",
                "rf = RandomForestClassifier(n_estimators=100, max_depth=10, class_weight=\"balanced\", random_state=42)\n",
                "rf.fit(X_train_scaled, y_train)\n",
                "y_val_rf = rf.predict(X_val_scaled)\n",
                "y_prob_rf = rf.predict_proba(X_val_scaled)[:, 1]\n",
                "\n",
                "results = [\n",
                "    evaluate_model(\"1. Majority Class\", y_val, y_val_majority),\n",
                "    evaluate_model(\"2. Static Weak-Label Rule\", y_val, y_val_rule),\n",
                "    evaluate_model(\"3. Logistic Regression\", y_val, y_val_lr, y_prob_lr),\n",
                "    evaluate_model(\"4. Random Forest (Uncalibrated)\", y_val, y_val_rf, y_prob_rf),\n",
                "]\n",
                "df_results = pd.DataFrame(results)\n",
                "print(df_results.to_string(index=False))\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 4 — Probability Calibration & Uncertainty Abstention\n",
                "\n",
                "Probabilities produced by decision trees are often uncalibrated step-functions. We apply **Sigmoid Calibration** on validation data to ensure predicted probabilities correspond to real empirical frequencies and implement explicit abstention (`uncertain`).\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "try:\n",
                "    from sklearn.frozen import FrozenEstimator\n",
                "    calibrated_rf = CalibratedClassifierCV(estimator=FrozenEstimator(rf), method=\"sigmoid\")\n",
                "except ImportError:\n",
                "    calibrated_rf = CalibratedClassifierCV(estimator=rf, method=\"sigmoid\", cv=\"prefit\")\n",
                "\n",
                "calibrated_rf.fit(X_val_scaled, y_val)\n",
                "\n",
                "# Evaluate on Test Split (held-out February test)\n",
                "y_test_pred = calibrated_rf.predict(X_test_scaled)\n",
                "y_test_prob = calibrated_rf.predict_proba(X_test_scaled)[:, 1]\n",
                "\n",
                "test_res = evaluate_model(\"5. Calibrated Random Forest (Test Set)\", y_test, y_test_pred, y_test_prob)\n",
                "print(\"\\n--- Final Test Set Results ---\")\n",
                "for k, v in test_res.items():\n",
                "    print(f\"  {k:<20}: {v:.4f}\" if isinstance(v, float) else f\"  {k:<20}: {v}\")\n",
                "\n",
                "# Abstention analysis\n",
                "abstention_threshold = 0.60\n",
                "uncertain_mask = (y_test_prob > (1.0 - abstention_threshold)) & (y_test_prob < abstention_threshold)\n",
                "abstention_pct = np.mean(uncertain_mask) * 100.0\n",
                "print(f\"\\n[*] Abstention Rate on Test Set: {abstention_pct:.2f}% ({np.sum(uncertain_mask)}/{len(y_test)} events)\")\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 5 — Serialization & Practical 9 Gate Sign-Off\n",
                "\n",
                "Export the trained, calibrated pipeline artifact to `models/classifier.joblib` for deployment in the live streaming engine.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "artifact = {\n",
                "    \"model_version\": \"practical-09-rf-v1.0\",\n",
                "    \"model_type\": \"calibrated_rf\",\n",
                "    \"model\": calibrated_rf,\n",
                "    \"scaler\": scaler,\n",
                "    \"feature_names\": active_feature_names,\n",
                "    \"feature_dim\": len(active_feature_names),\n",
                "    \"abstention_threshold\": 0.60,\n",
                "    \"trained_timestamp\": datetime.now(timezone.utc).isoformat(),\n",
                "    \"test_metrics\": test_res,\n",
                "}\n",
                "os.makedirs(\"../models\", exist_ok=True)\n",
                "joblib.dump(artifact, \"../models/classifier.joblib\")\n",
                "print(\"[SUCCESS] Practical 9 complete. Winning artifact saved to models/classifier.joblib\")\n",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.11",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

output_file = os.path.join(os.path.dirname(__file__), "..", "notebooks", "practical_09_classification.ipynb")
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)
print(f"[*] Generated {output_file} successfully.")
